name = "2 panes tab config 2"

[[panes]]
id = "p1"
split = "vertical"
children = [
    "p2",
    "p3",
]

[[panes]]
id = "p2"
type = "terminal"
is_focused = true
directory = "~"

[[panes]]
id = "p3"
type = "terminal"
directory = "~/Downloads"

[params]
